server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
#    instance-id: ${spring.application.name}:${instanceId:${random.value}}

spring:

  application:
    name: department-service

  #   ===============================
  #   H2 - DATA SOURCE
  #   ===============================
  datasource:
    url: jdbc:h2:file:~/Personal/office/db/departments;AUTO_SERVER=TRUE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          non_contextual_creation: false
  sql:
    init:
      continue-on-error: true
